# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Run Smoke Test

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'url'
        required: true
      username:
        description: 'username'
        required: true
        default: 'admin'
      password:
        description: 'password'
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - uses: mad9000/actions-find-and-replace-string@3
      id: pwd
      with:
          source: ${{ github.event.inputs.password }} # this translates to ref/heads/main on the main branch, but can be any arbitrary string 
          find: '$'        # we want to remove ref/heads/ from source 
          replace: '\$'
          replaceAll: true
    - uses: browser-actions/setup-chrome@latest
    - run: chrome --version
    - name: Build with Maven
      run: mvn -B clean test -Dconfig=in -Dpassword=${{steps.pwd.outputs.value}}

    - name: Report
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: allure-results
        retention-days: 5
    - name: Email Report
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: email report
        path: test-output/emailable-report
        retention-days: 5
    - name: Full
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: full file
        path: ./
        retention-days: 5

        

